blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Floffah/cltabbed/discussions
    about: Questions and feature ideas go here.
  - name: Creator's Discord Server
    url: https://discord.gg/bc8Y2y9
    about: If you need to ask the creator a direct question, go here.
